/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as R404RouteImport } from './../../routes/404'
import { Route as R401RouteImport } from './../../routes/401'
import { Route as publicRouteRouteImport } from './../../routes/(public)/route'
import { Route as protectedRouteRouteImport } from './../../routes/(protected)/route'
import { Route as IndexRouteImport } from './../../routes/index'
import { Route as publicSignUpRouteImport } from './../../routes/(public)/sign-up'
import { Route as publicLoginRouteImport } from './../../routes/(public)/login'
import { Route as protectedIconRouteImport } from './../../routes/(protected)/icon'
import { Route as protectedHashIdRouteImport } from './../../routes/(protected)/hashId'
import { Route as protectedHanbiroTaskRouteImport } from './../../routes/(protected)/hanbiroTask'
import { Route as protectedDemoComponentRouteImport } from './../../routes/(protected)/demoComponent'
import { Route as protectedFinancialRouteRouteImport } from './../../routes/(protected)/financial/route'
import { Route as protectedFinancialIndexRouteImport } from './../../routes/(protected)/financial/index'
import { Route as protectedFinancialWalletRouteImport } from './../../routes/(protected)/financial/wallet'
import { Route as protectedFinancialTransactionRouteImport } from './../../routes/(protected)/financial/transaction'
import { Route as protectedFinancialSettingRouteImport } from './../../routes/(protected)/financial/setting'
import { Route as protectedFinancialCategoryRouteImport } from './../../routes/(protected)/financial/category'
import { Route as protectedDemoTableRouteImport } from './../../routes/(protected)/demo/table'
import { Route as protectedDemoButtonRouteImport } from './../../routes/(protected)/demo/button'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedIconRoute = protectedIconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedHashIdRoute = protectedHashIdRouteImport.update({
  id: '/hashId',
  path: '/hashId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedHanbiroTaskRoute = protectedHanbiroTaskRouteImport.update({
  id: '/hanbiroTask',
  path: '/hanbiroTask',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDemoComponentRoute = protectedDemoComponentRouteImport.update({
  id: '/demoComponent',
  path: '/demoComponent',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedFinancialRouteRoute = protectedFinancialRouteRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedFinancialIndexRoute = protectedFinancialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedFinancialRouteRoute,
} as any)
const protectedFinancialWalletRoute =
  protectedFinancialWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => protectedFinancialRouteRoute,
  } as any)
const protectedFinancialTransactionRoute =
  protectedFinancialTransactionRouteImport.update({
    id: '/transaction',
    path: '/transaction',
    getParentRoute: () => protectedFinancialRouteRoute,
  } as any)
const protectedFinancialSettingRoute =
  protectedFinancialSettingRouteImport.update({
    id: '/setting',
    path: '/setting',
    getParentRoute: () => protectedFinancialRouteRoute,
  } as any)
const protectedFinancialCategoryRoute =
  protectedFinancialCategoryRouteImport.update({
    id: '/category',
    path: '/category',
    getParentRoute: () => protectedFinancialRouteRoute,
  } as any)
const protectedDemoTableRoute = protectedDemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDemoButtonRoute = protectedDemoButtonRouteImport.update({
  id: '/demo/button',
  path: '/demo/button',
  getParentRoute: () => protectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/404': typeof R404Route
  '/financial': typeof protectedFinancialRouteRouteWithChildren
  '/demoComponent': typeof protectedDemoComponentRoute
  '/hanbiroTask': typeof protectedHanbiroTaskRoute
  '/hashId': typeof protectedHashIdRoute
  '/icon': typeof protectedIconRoute
  '/login': typeof publicLoginRoute
  '/sign-up': typeof publicSignUpRoute
  '/demo/button': typeof protectedDemoButtonRoute
  '/demo/table': typeof protectedDemoTableRoute
  '/financial/category': typeof protectedFinancialCategoryRoute
  '/financial/setting': typeof protectedFinancialSettingRoute
  '/financial/transaction': typeof protectedFinancialTransactionRoute
  '/financial/wallet': typeof protectedFinancialWalletRoute
  '/financial/': typeof protectedFinancialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/404': typeof R404Route
  '/demoComponent': typeof protectedDemoComponentRoute
  '/hanbiroTask': typeof protectedHanbiroTaskRoute
  '/hashId': typeof protectedHashIdRoute
  '/icon': typeof protectedIconRoute
  '/login': typeof publicLoginRoute
  '/sign-up': typeof publicSignUpRoute
  '/demo/button': typeof protectedDemoButtonRoute
  '/demo/table': typeof protectedDemoTableRoute
  '/financial/category': typeof protectedFinancialCategoryRoute
  '/financial/setting': typeof protectedFinancialSettingRoute
  '/financial/transaction': typeof protectedFinancialTransactionRoute
  '/financial/wallet': typeof protectedFinancialWalletRoute
  '/financial': typeof protectedFinancialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/401': typeof R401Route
  '/404': typeof R404Route
  '/(protected)/financial': typeof protectedFinancialRouteRouteWithChildren
  '/(protected)/demoComponent': typeof protectedDemoComponentRoute
  '/(protected)/hanbiroTask': typeof protectedHanbiroTaskRoute
  '/(protected)/hashId': typeof protectedHashIdRoute
  '/(protected)/icon': typeof protectedIconRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(protected)/demo/button': typeof protectedDemoButtonRoute
  '/(protected)/demo/table': typeof protectedDemoTableRoute
  '/(protected)/financial/category': typeof protectedFinancialCategoryRoute
  '/(protected)/financial/setting': typeof protectedFinancialSettingRoute
  '/(protected)/financial/transaction': typeof protectedFinancialTransactionRoute
  '/(protected)/financial/wallet': typeof protectedFinancialWalletRoute
  '/(protected)/financial/': typeof protectedFinancialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/404'
    | '/financial'
    | '/demoComponent'
    | '/hanbiroTask'
    | '/hashId'
    | '/icon'
    | '/login'
    | '/sign-up'
    | '/demo/button'
    | '/demo/table'
    | '/financial/category'
    | '/financial/setting'
    | '/financial/transaction'
    | '/financial/wallet'
    | '/financial/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/401'
    | '/404'
    | '/demoComponent'
    | '/hanbiroTask'
    | '/hashId'
    | '/icon'
    | '/login'
    | '/sign-up'
    | '/demo/button'
    | '/demo/table'
    | '/financial/category'
    | '/financial/setting'
    | '/financial/transaction'
    | '/financial/wallet'
    | '/financial'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/(public)'
    | '/401'
    | '/404'
    | '/(protected)/financial'
    | '/(protected)/demoComponent'
    | '/(protected)/hanbiroTask'
    | '/(protected)/hashId'
    | '/(protected)/icon'
    | '/(public)/login'
    | '/(public)/sign-up'
    | '/(protected)/demo/button'
    | '/(protected)/demo/table'
    | '/(protected)/financial/category'
    | '/(protected)/financial/setting'
    | '/(protected)/financial/transaction'
    | '/(protected)/financial/wallet'
    | '/(protected)/financial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  R401Route: typeof R401Route
  R404Route: typeof R404Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/icon': {
      id: '/(protected)/icon'
      path: '/icon'
      fullPath: '/icon'
      preLoaderRoute: typeof protectedIconRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/hashId': {
      id: '/(protected)/hashId'
      path: '/hashId'
      fullPath: '/hashId'
      preLoaderRoute: typeof protectedHashIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/hanbiroTask': {
      id: '/(protected)/hanbiroTask'
      path: '/hanbiroTask'
      fullPath: '/hanbiroTask'
      preLoaderRoute: typeof protectedHanbiroTaskRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/demoComponent': {
      id: '/(protected)/demoComponent'
      path: '/demoComponent'
      fullPath: '/demoComponent'
      preLoaderRoute: typeof protectedDemoComponentRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/financial': {
      id: '/(protected)/financial'
      path: '/financial'
      fullPath: '/financial'
      preLoaderRoute: typeof protectedFinancialRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/financial/': {
      id: '/(protected)/financial/'
      path: '/'
      fullPath: '/financial/'
      preLoaderRoute: typeof protectedFinancialIndexRouteImport
      parentRoute: typeof protectedFinancialRouteRoute
    }
    '/(protected)/financial/wallet': {
      id: '/(protected)/financial/wallet'
      path: '/wallet'
      fullPath: '/financial/wallet'
      preLoaderRoute: typeof protectedFinancialWalletRouteImport
      parentRoute: typeof protectedFinancialRouteRoute
    }
    '/(protected)/financial/transaction': {
      id: '/(protected)/financial/transaction'
      path: '/transaction'
      fullPath: '/financial/transaction'
      preLoaderRoute: typeof protectedFinancialTransactionRouteImport
      parentRoute: typeof protectedFinancialRouteRoute
    }
    '/(protected)/financial/setting': {
      id: '/(protected)/financial/setting'
      path: '/setting'
      fullPath: '/financial/setting'
      preLoaderRoute: typeof protectedFinancialSettingRouteImport
      parentRoute: typeof protectedFinancialRouteRoute
    }
    '/(protected)/financial/category': {
      id: '/(protected)/financial/category'
      path: '/category'
      fullPath: '/financial/category'
      preLoaderRoute: typeof protectedFinancialCategoryRouteImport
      parentRoute: typeof protectedFinancialRouteRoute
    }
    '/(protected)/demo/table': {
      id: '/(protected)/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof protectedDemoTableRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/demo/button': {
      id: '/(protected)/demo/button'
      path: '/demo/button'
      fullPath: '/demo/button'
      preLoaderRoute: typeof protectedDemoButtonRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface protectedFinancialRouteRouteChildren {
  protectedFinancialCategoryRoute: typeof protectedFinancialCategoryRoute
  protectedFinancialSettingRoute: typeof protectedFinancialSettingRoute
  protectedFinancialTransactionRoute: typeof protectedFinancialTransactionRoute
  protectedFinancialWalletRoute: typeof protectedFinancialWalletRoute
  protectedFinancialIndexRoute: typeof protectedFinancialIndexRoute
}

const protectedFinancialRouteRouteChildren: protectedFinancialRouteRouteChildren =
  {
    protectedFinancialCategoryRoute: protectedFinancialCategoryRoute,
    protectedFinancialSettingRoute: protectedFinancialSettingRoute,
    protectedFinancialTransactionRoute: protectedFinancialTransactionRoute,
    protectedFinancialWalletRoute: protectedFinancialWalletRoute,
    protectedFinancialIndexRoute: protectedFinancialIndexRoute,
  }

const protectedFinancialRouteRouteWithChildren =
  protectedFinancialRouteRoute._addFileChildren(
    protectedFinancialRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedFinancialRouteRoute: typeof protectedFinancialRouteRouteWithChildren
  protectedDemoComponentRoute: typeof protectedDemoComponentRoute
  protectedHanbiroTaskRoute: typeof protectedHanbiroTaskRoute
  protectedHashIdRoute: typeof protectedHashIdRoute
  protectedIconRoute: typeof protectedIconRoute
  protectedDemoButtonRoute: typeof protectedDemoButtonRoute
  protectedDemoTableRoute: typeof protectedDemoTableRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedFinancialRouteRoute: protectedFinancialRouteRouteWithChildren,
  protectedDemoComponentRoute: protectedDemoComponentRoute,
  protectedHanbiroTaskRoute: protectedHanbiroTaskRoute,
  protectedHashIdRoute: protectedHashIdRoute,
  protectedIconRoute: protectedIconRoute,
  protectedDemoButtonRoute: protectedDemoButtonRoute,
  protectedDemoTableRoute: protectedDemoTableRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicLoginRoute: typeof publicLoginRoute
  publicSignUpRoute: typeof publicSignUpRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicLoginRoute: publicLoginRoute,
  publicSignUpRoute: publicSignUpRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  R401Route: R401Route,
  R404Route: R404Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
