export enum FINANCIAL_TRANSACTION_TYPE {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
  TRANSFER = 'TRANSFER',
}

export class FinancialTransactionTypeHelper {}

export enum FINANCIAL_TRANSACTION_STATUS {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export const FINANCIAL_TRANSACTION_STATUS_LABEL: Record<
  FINANCIAL_TRANSACTION_STATUS,
  { color: string }
> = {
  [FINANCIAL_TRANSACTION_STATUS.COMPLETED]: { color: 'success' },
  [FINANCIAL_TRANSACTION_STATUS.PENDING]: { color: 'warning' },
  [FINANCIAL_TRANSACTION_STATUS.FAILED]: { color: 'error' },
}
