/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R404RouteImport } from './routes/404'
import { Route as R401RouteImport } from './routes/401'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as publicTaskRouteImport } from './routes/(public)/task'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicIconRouteImport } from './routes/(public)/icon'
import { Route as publicHashIdRouteImport } from './routes/(public)/hashId'
import { Route as publicDemoComponentRouteImport } from './routes/(public)/demoComponent'
import { Route as protectedDashboardRouteRouteImport } from './routes/(protected)/dashboard/route'
import { Route as publicDemoTableRouteImport } from './routes/(public)/demo/table'
import { Route as publicDemoButtonRouteImport } from './routes/(public)/demo/button'

const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicTaskRoute = publicTaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicIconRoute = publicIconRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicHashIdRoute = publicHashIdRouteImport.update({
  id: '/hashId',
  path: '/hashId',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicDemoComponentRoute = publicDemoComponentRouteImport.update({
  id: '/demoComponent',
  path: '/demoComponent',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedDashboardRouteRoute = protectedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const publicDemoTableRoute = publicDemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicDemoButtonRoute = publicDemoButtonRouteImport.update({
  id: '/demo/button',
  path: '/demo/button',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/404': typeof R404Route
  '/dashboard': typeof protectedDashboardRouteRoute
  '/demoComponent': typeof publicDemoComponentRoute
  '/hashId': typeof publicHashIdRoute
  '/icon': typeof publicIconRoute
  '/login': typeof publicLoginRoute
  '/task': typeof publicTaskRoute
  '/demo/button': typeof publicDemoButtonRoute
  '/demo/table': typeof publicDemoTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/404': typeof R404Route
  '/dashboard': typeof protectedDashboardRouteRoute
  '/demoComponent': typeof publicDemoComponentRoute
  '/hashId': typeof publicHashIdRoute
  '/icon': typeof publicIconRoute
  '/login': typeof publicLoginRoute
  '/task': typeof publicTaskRoute
  '/demo/button': typeof publicDemoButtonRoute
  '/demo/table': typeof publicDemoTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/401': typeof R401Route
  '/404': typeof R404Route
  '/(protected)/dashboard': typeof protectedDashboardRouteRoute
  '/(public)/demoComponent': typeof publicDemoComponentRoute
  '/(public)/hashId': typeof publicHashIdRoute
  '/(public)/icon': typeof publicIconRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/task': typeof publicTaskRoute
  '/(public)/demo/button': typeof publicDemoButtonRoute
  '/(public)/demo/table': typeof publicDemoTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/404'
    | '/dashboard'
    | '/demoComponent'
    | '/hashId'
    | '/icon'
    | '/login'
    | '/task'
    | '/demo/button'
    | '/demo/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/401'
    | '/404'
    | '/dashboard'
    | '/demoComponent'
    | '/hashId'
    | '/icon'
    | '/login'
    | '/task'
    | '/demo/button'
    | '/demo/table'
  id:
    | '__root__'
    | '/'
    | '/(protected)'
    | '/(public)'
    | '/401'
    | '/404'
    | '/(protected)/dashboard'
    | '/(public)/demoComponent'
    | '/(public)/hashId'
    | '/(public)/icon'
    | '/(public)/login'
    | '/(public)/task'
    | '/(public)/demo/button'
    | '/(public)/demo/table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  R401Route: typeof R401Route
  R404Route: typeof R404Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/task': {
      id: '/(public)/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof publicTaskRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/icon': {
      id: '/(public)/icon'
      path: '/icon'
      fullPath: '/icon'
      preLoaderRoute: typeof publicIconRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/hashId': {
      id: '/(public)/hashId'
      path: '/hashId'
      fullPath: '/hashId'
      preLoaderRoute: typeof publicHashIdRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/demoComponent': {
      id: '/(public)/demoComponent'
      path: '/demoComponent'
      fullPath: '/demoComponent'
      preLoaderRoute: typeof publicDemoComponentRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(public)/demo/table': {
      id: '/(public)/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof publicDemoTableRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/demo/button': {
      id: '/(public)/demo/button'
      path: '/demo/button'
      fullPath: '/demo/button'
      preLoaderRoute: typeof publicDemoButtonRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface protectedRouteRouteChildren {
  protectedDashboardRouteRoute: typeof protectedDashboardRouteRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedDashboardRouteRoute: protectedDashboardRouteRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicDemoComponentRoute: typeof publicDemoComponentRoute
  publicHashIdRoute: typeof publicHashIdRoute
  publicIconRoute: typeof publicIconRoute
  publicLoginRoute: typeof publicLoginRoute
  publicTaskRoute: typeof publicTaskRoute
  publicDemoButtonRoute: typeof publicDemoButtonRoute
  publicDemoTableRoute: typeof publicDemoTableRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicDemoComponentRoute: publicDemoComponentRoute,
  publicHashIdRoute: publicHashIdRoute,
  publicIconRoute: publicIconRoute,
  publicLoginRoute: publicLoginRoute,
  publicTaskRoute: publicTaskRoute,
  publicDemoButtonRoute: publicDemoButtonRoute,
  publicDemoTableRoute: publicDemoTableRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  R401Route: R401Route,
  R404Route: R404Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
